apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: service-c-destination-rule
  namespace: custom
spec:
  host: service-c.custom.svc.cluster.local
  trafficPolicy:
    loadBalancer:
      simple: PASSTHROUGH  # 로드 밸런싱 비활성화
