apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: service-c-ip2-entry
  namespace: custom
spec:
  hosts:
  - "service-c-ip2-routing"
  addresses:
  - 172.31.233.209  # 두 번째 Pod IP
  ports:
  - number: 11002
    name: http
    protocol: HTTP
  resolution: STATIC
  location: MESH_INTERNAL
  endpoints:
  - address: 172.31.233.209  # 두 번째 Pod IP
    ports:
      http: 11002
