apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: service-c-ip1-entry
  namespace: custom
spec:
  hosts:
  - "service-c-ip1-routing"
  addresses:
  - 172.20.235.145  # 첫 번째 Pod IP
  ports:
  - number: 11002
    name: http
    protocol: HTTP
  resolution: STATIC
  location: MESH_INTERNAL
  endpoints:
  - address: 172.20.235.145  # 첫 번째 Pod IP
    ports:
      http: 11002
