apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: productpage-filter
  namespace: bookinfo
spec:
  workloadSelector:
    labels:
      app: productpage
  configPatches:
  - applyTo: HTTP_FILTER
    match:
      context: SIDECAR_OUTBOUND
      listener:
        filterChain:
          filter:
            name: envoy.filters.network.http_connection_manager
    patch:
      operation: INSERT_BEFORE
      value:
        name: envoy.filters.http.lua
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.http.lua.v3.Lua
          inline_code: |
            local pod_ip = nil

            function envoy_on_request(request_handle)
              if not pod_ip then
                local handle = io.popen("hostname -i")
                pod_ip = handle:read("*a"):match("^%s*(.-)%s*$")
                handle:close()
              end

              local rand = math.random(0, 100)
              local destination = request_handle:headers():get(":authority")
              local domain = destination:match("^([^:]+)")

              if domain == "details" then
                if pod_ip == "172.24.182.25" then
                  if rand <= 34 then
                    destination = "172.24.182.26"
                  end
                  if rand <= 67 then
                    destination = "172.31.71.239"
                  end
                  if rand <= 100 then
                    destination = "172.20.235.157"
                  end
                end
                if pod_ip == "172.31.71.237" then
                  if rand <= 34 then
                    destination = "172.24.182.26"
                  end
                  if rand <= 67 then
                    destination = "172.31.71.239"
                  end
                  if rand <= 100 then
                    destination = "172.20.235.157"
                  end
                end
              end
              if domain == "reviews" then
                if pod_ip == "172.24.182.25" then
                  if rand <= 34 then
                    destination = "172.24.182.27"
                  end
                  if rand <= 67 then
                    destination = "172.31.71.240"
                  end
                  if rand <= 100 then
                    destination = "172.20.235.159"
                  end
                end
                if pod_ip == "172.31.71.237" then
                  if rand <= 34 then
                    destination = "172.24.182.27"
                  end
                  if rand <= 67 then
                    destination = "172.31.71.240"
                  end
                  if rand <= 100 then
                    destination = "172.20.235.159"
                  end
                end
              end
              request_handle:headers():replace(":authority", destination)
            end
