apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: service-a-filter
  namespace: custom
spec:
  workloadSelector:
    labels:
      app: service-a
  configPatches:
  - applyTo: HTTP_FILTER
    match:
      context: SIDECAR_OUTBOUND
      listener:
        filterChain:
          filter:
            name: envoy.filters.network.http_connection_manager
    patch:
      operation: INSERT_BEFORE
      value:
        name: envoy.filters.http.lua
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.http.lua.v3.Lua
          inline_code: |
            local pod_ip = nil

            function envoy_on_request(request_handle)
              if not pod_ip then
                local handle = io.popen("hostname -i")
                pod_ip = handle:read("*a"):match("^%s*(.-)%s*$")
                handle:close()
              end

              local rand = math.random(0, 100)
              local destination = request_handle:headers():get(":authority")
              local domain = destination:match("^([^:]+)")

              if domain == "service-b" then
                  if pod_ip == "172.24.182.6" then
                      if rand <= 25 then
                        destination = "172.22.33.6" .. destination:match("(:.*)$")
                      elseif rand <= 50 then
                        destination = "172.20.235.141" .. destination:match("(:.*)$")
                      elseif rand <= 75 then
                        destination = "172.31.233.204" .. destination:match("(:.*)$")
                      elseif rand <= 100 then
                        destination = "172.24.182.7" .. destination:match("(:.*)$")
                      end
                  elseif pod_ip == "172.20.235.142" then
                      if rand <= 25 then
                        destination = "172.22.33.6" .. destination:match("(:.*)$")
                      elseif rand <= 50 then
                        destination = "172.20.235.141" .. destination:match("(:.*)$")
                      elseif rand <= 75 then
                        destination = "172.31.233.204" .. destination:match("(:.*)$")
                      elseif rand <= 100 then
                        destination = "172.24.182.7" .. destination:match("(:.*)$")
                      end
                  elseif pod_ip == "172.31.233.202" then
                      if rand <= 25 then
                        destination = "172.22.33.6" .. destination:match("(:.*)$")
                      elseif rand <= 50 then
                        destination = "172.20.235.141" .. destination:match("(:.*)$")
                      elseif rand <= 75 then
                        destination = "172.31.233.204" .. destination:match("(:.*)$")
                      elseif rand <= 100 then
                        destination = "172.24.182.7" .. destination:match("(:.*)$")
                      end
                  end
              end
              request_handle:headers():replace(":authority", destination)
            end
