apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: service-b-filter
  namespace: custom
spec:
  configPatches:
  - applyTo: HTTP_FILTER  # HTTP 요청에 대해 필터 적용
    match:
      context: SIDECAR_OUTBOUND  # 아웃바운드 요청에 적용
      listener:
        filterChain:
          filter:
            name: envoy.filters.network.http_connection_manager  # HTTP 연결 관리 필터
    patch:
      operation: INSERT_FIRST  # 필터 체인에서 가장 먼저 실행
      value:
        name: envoy.filters.http.lua  # Lua 필터 사용
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.http.lua.v3.Lua
          inline_code: |
            function envoy_on_request(request_handle)
              -- 요청의 :authority 헤더에서 클러스터 이름과 포트 추출
              local destination = request_handle:headers():get(":authority")
              
              -- 클러스터 이름 매칭 (예: service-c:11002)
              if destination == "service-c:11002" then
                -- 로그로 필터 동작 확인
                request_handle:logInfo("Changing destination to pod IP")

                -- 헤더를 파드 IP로 명시적으로 변경
                request_handle:headers():replace(":authority", "172.31.233.209:11002")
                request_handle:headers():replace("Host", "172.31.233.209:11002")

                -- 필요시 다른 헤더도 수정 가능
              end
            end

